const sampleDay = {
  label: 'Day 02',
  date: 'March 12, 2026',
  location: 'Kyoto, Japan',
  items: [
    {
      time: '8:00 AM',
      title: 'Breakfast at Nishiki Market',
      description: 'Sample fresh mochi and grilled skewers through the historic covered market.',
      cost: '$12',
    },
    {
      time: '9:30 AM',
      title: 'Fushimi Inari Shrine hike',
      description: 'Walk beneath thousands of vermilion torii gates up the mountain trail.',
      cost: 'Free',
    },
    {
      time: '1:00 PM',
      title: 'Lunch — kaiseki tasting menu',
      description: 'A multi-course seasonal meal at a quiet spot near the Kamo River.',
      cost: '$45',
    },
    {
      time: '3:00 PM',
      title: 'Arashiyama Bamboo Grove',
      description: 'Stroll the towering bamboo path before the evening crowds arrive.',
      cost: '$8',
    },
    {
      time: '7:00 PM',
      title: 'Gion district evening walk',
      description: 'Wander lantern-lit streets past traditional teahouses.',
      cost: 'Free',
    },
  ],
}

function ItineraryPreview() {
  return (
    <section className="relative py-24">
      <div className="mx-auto max-w-3xl px-6">
        <div className="mx-auto max-w-2xl text-center">
          <span className="text-xs font-semibold uppercase tracking-wide text-forest">
            See it in action
          </span>
          <h2 className="mt-3 font-display text-3xl text-charcoal sm:text-4xl">
            A real itinerary, generated by PlanIT
          </h2>
        </div>

        <div className="mt-10 flex items-center justify-between">
          <div>
            <h3 className="font-display text-2xl text-charcoal">{sampleDay.location}</h3>
            <p className="mt-1 text-sm text-warm-gray">
              {sampleDay.date} · $220 budget · 2 travelers · Adventure
            </p>
          </div>
          <span className="hidden shrink-0 rounded-2xl border border-terracotta bg-terracotta px-5 py-3 text-warm-white sm:block">
            <span className="block font-display text-base font-semibold">{sampleDay.label}</span>
            <span className="mt-0.5 block text-xs text-warm-white/80">{sampleDay.date}</span>
          </span>
        </div>

        <div className="mt-8">
          {sampleDay.items.map((item, index) => {
            const isLast = index === sampleDay.items.length - 1
            return (
              <div key={item.title} className="relative pl-12">
                {!isLast && <span className="absolute left-[19px] top-10 bottom-0 w-px bg-charcoal/10" />}
                <span className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-full border-2 border-terracotta bg-warm-white text-sm font-semibold text-terracotta">
                  {index + 1}
                </span>
                <div className="pb-8">
                  <div className="flex items-start justify-between gap-4 rounded-xl border border-warm-white/50 bg-warm-white/40 p-4 shadow-sm shadow-charcoal/5 backdrop-blur-xl">
                    <div>
                      <p className="text-sm font-medium text-warm-gray">{item.time}</p>
                      <p className="mt-0.5 text-charcoal">{item.title}</p>
                      <p className="mt-1 text-sm text-warm-gray">{item.description}</p>
                    </div>
                    <span className="shrink-0 rounded-full bg-sand/20 px-3 py-1 text-xs font-semibold text-terracotta">
                      {item.cost}
                    </span>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}

export default ItineraryPreview
